import { UserProfile, BankAccount, Transaction, TransactionType, TransactionStatus, Bill } from './types';

export const INITIAL_PROFILE: UserProfile = {
  name: 'أماني محمد فؤاد',
  ipa: 'amany.fouad@instapay',
  mobile: '01023456789',
  defaultBalance: 48250.75,
};

export const INITIAL_ACCOUNTS: BankAccount[] = [
  {
    id: 'nbe-debit',
    bankNameAr: 'البنك الأهلي المصري',
    bankNameEn: 'National Bank of Egypt',
    accountNumber: '•••• •••• •••• 5842',
    balance: 35120.50,
    isDefault: true,
    cardBrand: 'visa',
    cardColor: 'linear-gradient(135deg, #0f5132 0%, #198754 100%)', // NBE Green
  },
  {
    id: 'misr-debit',
    bankNameAr: 'بنك مصر',
    bankNameEn: 'Banque Misr',
    accountNumber: '•••• •••• •••• 9106',
    balance: 13130.25,
    isDefault: false,
    cardBrand: 'mastercard',
    cardColor: 'linear-gradient(135deg, #8c1d40 0%, #a21c4b 100%)', // Banque Misr Red/Crimson
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    referenceId: 'IP2026061900124875',
    type: TransactionType.RECEIVED,
    titleAr: 'وارد من محمد فؤاد السيد',
    titleEn: 'Received from Mohamed Fouad El-Sayed',
    subtitleAr: 'تحويل إلى عنوان الدفع IPN',
    subtitleEn: 'Transfer to IPN Address',
    amount: 15000.00,
    date: '2026-06-19T14:30:00Z',
    status: TransactionStatus.SUCCESS,
    senderNameAr: 'محمد فؤاد السيد',
    senderNameEn: 'Mohamed Fouad El-Sayed',
    receiverNameAr: 'أماني محمد فؤاد',
    receiverNameEn: 'Amany Mohamed Fouad',
    receiverAccountOrIpa: 'amany.fouad@instapay',
    note: 'مصاريف المنزل الشهرية',
  },
  {
    id: 'tx-2',
    referenceId: 'IP2026061800921045',
    type: TransactionType.TRANSFER_IPA,
    titleAr: 'تحويل إلى كريم أشرف',
    titleEn: 'Transfer to Karim Ashraf',
    subtitleAr: 'تحويل سريع عبر عنوان الدفع',
    subtitleEn: 'Instant Transfer via IPA',
    amount: 4500.00,
    date: '2026-06-18T19:15:00Z',
    status: TransactionStatus.SUCCESS,
    senderNameAr: 'أماني محمد فؤاد',
    senderNameEn: 'Amany Mohamed Fouad',
    receiverNameAr: 'كريم أشرف عبد العزيز',
    receiverNameEn: 'Karim Ashraf Abdel-Aziz',
    receiverAccountOrIpa: 'karim.ashraf@instapay',
    note: 'اشتراك النادي الصيفي',
  },
  {
    id: 'tx-3',
    referenceId: 'IP2026061700551241',
    type: TransactionType.BILL_PAYMENT,
    titleAr: 'فاتورة شركة الغاز (تاون جاس)',
    titleEn: 'Gas Bill (Town Gas)',
    subtitleAr: 'مدفوعات فواتير فوري',
    subtitleEn: 'Fawry Bill Payments',
    amount: 420.00,
    date: '2026-06-17T09:45:00Z',
    status: TransactionStatus.SUCCESS,
    senderNameAr: 'أماني محمد فؤاد',
    senderNameEn: 'Amany Mohamed Fouad',
    bankNameAr: 'البنك الأهلي المصري',
    bankNameEn: 'National Bank of Egypt',
    note: 'شقة المهندسين - يونيو 2026',
  },
  {
    id: 'tx-4',
    referenceId: 'IP2026061600329014',
    type: TransactionType.MOBILE_RECHARGE,
    titleAr: 'شحن رصيد فودافون كارت',
    titleEn: 'Vodafone Mobile Recharge',
    subtitleAr: 'شحن سريع لرقم 01014859620',
    subtitleEn: 'Instant Recharge for 01014859620',
    amount: 150.00,
    date: '2026-06-16T11:20:00Z',
    status: TransactionStatus.SUCCESS,
    senderNameAr: 'أماني محمد فؤاد',
    senderNameEn: 'Amany Mohamed Fouad',
    bankNameAr: 'بنك مصر',
    bankNameEn: 'Banque Misr',
    note: 'شحن رصيد هوائي',
  },
  {
    id: 'tx-5',
    referenceId: 'IP2026061500847120',
    type: TransactionType.TRANSFER_BANK,
    titleAr: 'تحويل إلى د. منى أحمد',
    titleEn: 'Transfer to Dr. Mona Ahmed',
    subtitleAr: 'تحويل لحساب بنكي - البنك التجاري الدولي',
    subtitleEn: 'Bank Account Transfer - CIB',
    amount: 8500.00,
    date: '2026-06-15T16:05:00Z',
    status: TransactionStatus.SUCCESS,
    senderNameAr: 'أماني محمد فؤاد',
    senderNameEn: 'Amany Mohamed Fouad',
    receiverNameAr: 'منى أحمد الشناوي',
    receiverNameEn: 'Mona Ahmed El-Shenawy',
    receiverAccountOrIpa: 'EG82000300120158496201041', // IBAN
    bankNameAr: 'البنك التجاري الدولي (CIB)',
    bankNameEn: 'Commercial International Bank (CIB)',
    note: 'كشف عيادة وقسط ميزان',
  },
  {
    id: 'tx-6',
    referenceId: 'IP2026061400213054',
    type: TransactionType.BILL_PAYMENT,
    titleAr: 'فاتورة الكهرباء (جنوب القاهرة)',
    titleEn: 'Electricity Bill (South Cairo)',
    subtitleAr: 'مدفوعات فواتير الشركة القابضة',
    subtitleEn: 'EEHC Bill Payments',
    amount: 1250.00,
    date: '2026-06-14T10:00:00Z',
    status: TransactionStatus.SUCCESS,
    senderNameAr: 'أماني محمد فؤاد',
    senderNameEn: 'Amany Mohamed Fouad',
    bankNameAr: 'البنك الأهلي المصري',
    bankNameEn: 'National Bank of Egypt',
  },
  {
    id: 'tx-7',
    referenceId: 'IP2026061200918452',
    type: TransactionType.TRANSFER_WALLET,
    titleAr: 'تحويل إلى محفظة فودافون كاش',
    titleEn: 'Transfer to Vodafone Cash',
    subtitleAr: 'تحويل لمحفظة هاتف 01099887766',
    subtitleEn: 'Mobile Wallet Transfer 01099887766',
    amount: 2300.00,
    date: '2026-06-12T21:40:00Z',
    status: TransactionStatus.SUCCESS,
    senderNameAr: 'أماني محمد فؤاد',
    senderNameEn: 'Amany Mohamed Fouad',
    receiverNameAr: 'ياسر محمد فؤاد',
    receiverNameEn: 'Yasser Mohamed Fouad',
    receiverAccountOrIpa: '01099887766',
    note: 'تحويل عائلي سريع',
  }
];

export const INITIAL_BILLS: Bill[] = [
  {
    id: 'bill-1',
    providerAr: 'المصرية للاتصالات WE (إنترنت منزلي)',
    providerEn: 'Telecom Egypt WE (Home Internet)',
    categoryAr: 'إنترنت منزلي فوري',
    categoryEn: 'Home Internet Payment',
    amount: 380.00,
    dueDate: '2026-06-25',
  },
  {
    id: 'bill-2',
    providerAr: 'شركة المياه (القاهرة الكبرى)',
    providerEn: 'Cairo Water Company',
    categoryAr: 'مياه الشرب والصرف',
    categoryEn: 'Drinking Water Utilities',
    amount: 140.00,
    dueDate: '2026-06-28',
  }
];
